import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression
import numpy as np
import os

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="Golden Village Analytics", layout="wide")

# --- COLOUR PALETTE ---
GV_GOLD  = "#e8a51e"
GV_BLACK = "#000000"
GV_DARK  = "#1a1a1a"   # softer black for backgrounds
GV_MID   = "#2e2e2e"   # card / sidebar background
GV_LIGHT = "#f5f0e8"   # warm off-white for text on dark bg

# Discrete colour sequence: gold → amber shades → dark accents
GV_COLORS = [
    "#e8a51e", "#c98a0a", "#f0bc4a", "#a06d00",
    "#f5d080", "#7a5200", "#fce9b0", "#3d2900"
]

# --- CUSTOM CSS THEME ---
st.markdown("""
<style>
    /* ── App background ── */
    .stApp { background-color: #000000; }

    /* ── Sidebar ── */
    [data-testid="stSidebar"] {
        background-color: #1a1a1a;
        border-right: 2px solid #e8a51e;
    }
    [data-testid="stSidebar"] * { color: #f5f0e8 !important; }
    [data-testid="stSidebar"] .stRadio label { color: #e8a51e !important; }

    /* ── Main text ── */
    h1, h2, h3, h4, h5, h6 { color: #e8a51e !important; }
    p, li, span, div { color: #f5f0e8; }

    /* ── Metric cards ── */
    [data-testid="stMetric"] {
        background-color: #1a1a1a;
        border: 1px solid #e8a51e;
        border-radius: 8px;
        padding: 12px 16px;
    }
    [data-testid="stMetricLabel"] { color: #e8a51e !important; font-weight: 600; }
    [data-testid="stMetricValue"] { color: #f5f0e8 !important; font-size: 1.6rem !important; }

    /* ── Divider ── */
    hr { border-color: #e8a51e; opacity: 0.4; }

    /* ── Dataframe ── */
    [data-testid="stDataFrame"] { border: 1px solid #e8a51e; border-radius: 6px; }

    /* ── Multiselect tags ── */
    .stMultiSelect span[data-baseweb="tag"] {
        background-color: #e8a51e !important;
        color: #000000 !important;
    }

    /* ── Sidebar selectbox / multiselect border ── */
    [data-testid="stSidebar"] [data-baseweb="select"] > div,
    [data-testid="stSidebar"] [data-baseweb="input"] > div {
        border-color: #e8a51e !important;
        border-width: 1.5px !important;
        border-radius: 6px !important;
    }

    /* ── Sidebar multiselect label text → black for readability ── */
    [data-testid="stSidebar"] .stMultiSelect label,
    [data-testid="stSidebar"] .stSelectbox label {
        color: #000000 !important;
        font-weight: 600;
    }

    /* ── Checkbox ── */
    .stCheckbox label { color: #e8a51e !important; }

    /* ── Plotly chart container ── */
    .js-plotly-plot { border-radius: 8px; }
</style>
""", unsafe_allow_html=True)

# --- PLOTLY DARK TEMPLATE WITH GV COLOURS ---
import plotly.io as pio
pio.templates["gv_dark"] = pio.templates["plotly_dark"]
pio.templates["gv_dark"].layout.update(
    paper_bgcolor="#1a1a1a",
    plot_bgcolor="#1a1a1a",
    font_color="#f5f0e8",
    colorway=GV_COLORS,
    title_font_color="#e8a51e",
    legend_bgcolor="#2e2e2e",
    legend_bordercolor="#e8a51e",
    xaxis=dict(gridcolor="#2e2e2e", linecolor="#e8a51e", tickcolor="#e8a51e"),
    yaxis=dict(gridcolor="#2e2e2e", linecolor="#e8a51e", tickcolor="#e8a51e"),
)
pio.templates.default = "gv_dark"

# --- DATA LOADING (CACHED) ---
@st.cache_data
def load_data():
    """
    Loads all CSV data from the data/ folder.
    gv_customer_segments.csv is generated by running gv_analytics_main.py first.
    """
    try:
        movies_df    = pd.read_csv("data/gv_movies.csv")
        customers_df = pd.read_csv("data/gv_customers_set1.csv")
        bookings_df  = pd.read_csv("data/gv_bookings_set1.csv", parse_dates=["screening_date"])

        # Derive occupancy_rate if not already present
        if "occupancy_rate" not in bookings_df.columns:
            bookings_df["occupancy_rate"] = bookings_df["seats_sold"] / bookings_df["capacity"]

        occ_df = bookings_df.copy()

        # Load segments if available (generated by gv_analytics_main.py)
        segments_path = "data/gv_customer_segments.csv"
        if os.path.exists(segments_path):
            segments_df  = pd.read_csv(segments_path)
            cust_seg_df  = pd.merge(customers_df, segments_df[["customer_id","persona"]],
                                    on="customer_id", how="left")
        else:
            cust_seg_df = customers_df.copy()
            cust_seg_df["persona"] = "Run gv_analytics_main.py to generate segments"

        return movies_df, cust_seg_df, occ_df

    except FileNotFoundError as e:
        st.error(f"Data file not found: {e}. Ensure you are running this from the root directory and the data/ folder exists.")
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame()

# Load data
movies_df, cust_seg_df, occ_df = load_data()

# --- SIDEBAR NAVIGATION ---
st.sidebar.title("GV Analytics Menu")
page = st.sidebar.selectbox("Select Dashboard:", ["Customer Clustering", "Occupancy Analytics"])

# ══════════════════════════════════════════════════
# PAGE 1: CUSTOMER CLUSTERING
# ══════════════════════════════════════════════════
if page == "Customer Clustering":
    st.title("Customer Clustering & Segmentation")

    if not cust_seg_df.empty:
        segment_col = "persona"
        spend_col   = "total_spend"
        freq_col    = "total_visits"
        genre_col   = "favourite_genre"

        # --- SIDEBAR FILTERS ---
        st.sidebar.subheader("Clustering Filters")

        segment_options = cust_seg_df[segment_col].dropna().unique()
        selected_segments = st.sidebar.multiselect(
            "Select Customer Segments:",
            options=segment_options,
            default=segment_options
        )
        filtered_cust = cust_seg_df[cust_seg_df[segment_col].isin(selected_segments)]

        # --- KPIs ---
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Total Customers",  f"{len(filtered_cust):,}")
        col2.metric("Average Spend",    f"${filtered_cust[spend_col].mean():.2f}")
        col3.metric("Avg Visits",       f"{filtered_cust[freq_col].mean():.1f}")
        col4.metric("GV+ Members",
                    f"{filtered_cust['gv_plus_member'].sum():,}" if "gv_plus_member" in filtered_cust.columns else "N/A")

        st.markdown("---")

        # --- ROW 1: Segment Distribution + Spend vs Frequency ---
        col_chart1, col_chart2 = st.columns(2)

        with col_chart1:
            st.subheader("Segment Distribution")
            seg_counts = filtered_cust[segment_col].value_counts().reset_index()
            seg_counts.columns = [segment_col, "count"]
            fig_bar = px.bar(
                seg_counts, x=segment_col, y="count",
                labels={segment_col: "Segment", "count": "Number of Customers"},
                color=segment_col,
                color_discrete_sequence=GV_COLORS
            )
            fig_bar.update_layout(showlegend=False, xaxis_tickangle=-20)
            st.plotly_chart(fig_bar, use_container_width=True)

        with col_chart2:
            st.subheader("Spend vs. Visit Frequency by Segment")
            fig_scatter = px.scatter(
                filtered_cust, x=freq_col, y=spend_col,
                color=segment_col, hover_data=["customer_id"],
                labels={freq_col: "Total Visits", spend_col: "Total Spend (SGD)"},
                opacity=0.6,
                color_discrete_sequence=GV_COLORS
            )
            st.plotly_chart(fig_scatter, use_container_width=True)

        # --- ROW 2: Avg Spend per Segment + Favourite Genre Breakdown ---
        col_chart3, col_chart4 = st.columns(2)

        with col_chart3:
            st.subheader("Avg Spend & Visits per Segment")
            profile_df = (
                filtered_cust.groupby(segment_col)[[spend_col, freq_col, "avg_ticket_price"]]
                .mean().round(2).reset_index()
            )
            fig_profile = px.bar(
                profile_df, x=segment_col, y=spend_col,
                color=segment_col,
                color_discrete_sequence=GV_COLORS,
                labels={segment_col: "Segment", spend_col: "Avg Total Spend (SGD)"}
            )
            fig_profile.update_layout(showlegend=False, xaxis_tickangle=-20)
            st.plotly_chart(fig_profile, use_container_width=True)

        with col_chart4:
            st.subheader("Favourite Genre by Segment")
            if genre_col in filtered_cust.columns:
                genre_seg = (
                    filtered_cust.groupby([segment_col, genre_col])
                    .size().reset_index(name="count")
                )
                fig_genre = px.bar(
                    genre_seg, x=genre_col, y="count",
                    color=segment_col, barmode="group",
                    color_discrete_sequence=GV_COLORS,
                    labels={genre_col: "Genre", "count": "Customers"}
                )
                fig_genre.update_layout(xaxis_tickangle=-20)
                st.plotly_chart(fig_genre, use_container_width=True)
            else:
                st.info("Favourite genre column not found.")

        # --- SEGMENT PROFILE TABLE ---
        st.markdown("---")
        st.subheader("Segment Profile Summary")
        profile_table = (
            filtered_cust.groupby(segment_col)
            .agg(
                Customers      =(segment_col,   "count"),
                Avg_Spend      =(spend_col,      "mean"),
                Avg_Visits     =(freq_col,       "mean"),
                Avg_Recency    =("recency_days", "mean") if "recency_days" in filtered_cust.columns else (spend_col, "count"),
                GVPlus_Rate    =("gv_plus_member","mean") if "gv_plus_member" in filtered_cust.columns else (spend_col, "count"),
            )
            .round(2)
            .reset_index()
        )
        st.dataframe(profile_table, use_container_width=True)

# ══════════════════════════════════════════════════
# PAGE 2: OCCUPANCY ANALYTICS
# ══════════════════════════════════════════════════
elif page == "Occupancy Analytics":
    st.title("Occupancy Analytics")

    if not occ_df.empty:
        genre_col   = "genre"
        day_col     = "day_of_week"
        time_col    = "time_slot"
        loc_col     = "location"
        occ_col     = "occupancy_rate"
        rev_col     = "revenue"
        title_col   = "title"

        # --- SIDEBAR FILTERS ---
        st.sidebar.subheader("Occupancy Filters")

        selected_genres = st.sidebar.multiselect(
            "Filter by Genre:",
            options=sorted(occ_df[genre_col].dropna().unique()),
            default=sorted(occ_df[genre_col].dropna().unique())
        )

        day_order = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
        available_days = [d for d in day_order if d in occ_df[day_col].unique()]
        selected_days = st.sidebar.multiselect(
            "Filter by Day:",
            options=available_days,
            default=available_days
        )

        selected_locations = st.sidebar.multiselect(
            "Filter by Location:",
            options=sorted(occ_df[loc_col].dropna().unique()),
            default=sorted(occ_df[loc_col].dropna().unique())
        )

        # Apply filters
        filtered_occ = occ_df[
            occ_df[genre_col].isin(selected_genres) &
            occ_df[day_col].isin(selected_days) &
            occ_df[loc_col].isin(selected_locations)
        ]

        # --- KPIs ---
        col1, col2, col3, col4 = st.columns(4)
        top_movie   = filtered_occ[title_col].value_counts().index[0] if len(filtered_occ) > 0 else "N/A"
        total_rev   = filtered_occ[rev_col].sum() if rev_col in filtered_occ.columns else 0
        avg_occ     = filtered_occ[occ_col].mean() * 100 if len(filtered_occ) > 0 else 0

        col1.metric("Total Bookings",      f"{len(filtered_occ):,}")
        col2.metric("Avg. Occupancy Rate", f"{avg_occ:.1f}%")
        col3.metric("Total Revenue",       f"SGD {total_rev/1_000_000:.2f}M" if total_rev > 0 else "N/A")
        col4.metric("Top Movie",           top_movie)

        st.markdown("---")

        # --- ROW 1: Occupancy by Genre + Day of Week Trend ---
        col_chart1, col_chart2 = st.columns(2)

        with col_chart1:
            st.subheader("Avg Occupancy by Genre")
            genre_grp = (
                filtered_occ.groupby(genre_col)[occ_col]
                .mean().mul(100).round(1).reset_index()
                .sort_values(occ_col, ascending=False)
            )
            genre_grp.columns = [genre_col, "Avg Occupancy (%)"]
            fig_genre = px.bar(
                genre_grp, x=genre_col, y="Avg Occupancy (%)",
                color=genre_col,
                color_discrete_sequence=GV_COLORS,
                labels={genre_col: "Genre"}
            )
            fig_genre.update_layout(showlegend=False)
            st.plotly_chart(fig_genre, use_container_width=True)

        with col_chart2:
            st.subheader("Avg Occupancy by Day of Week")
            day_grp = (
                filtered_occ.groupby(day_col)[occ_col]
                .mean().mul(100).round(1)
                .reindex(day_order).reset_index()
            )
            day_grp.columns = [day_col, "Avg Occupancy (%)"]
            fig_day = px.line(
                day_grp, x=day_col, y="Avg Occupancy (%)",
                markers=True,
                labels={day_col: "Day of Week"},
                color_discrete_sequence=[GV_GOLD]
            )
            fig_day.update_traces(line_width=2.5, marker_size=8)
            st.plotly_chart(fig_day, use_container_width=True)

        # --- ROW 2: Occupancy by Time Slot + Location Revenue ---
        col_chart3, col_chart4 = st.columns(2)

        with col_chart3:
            st.subheader("Avg Occupancy by Time Slot")
            time_order = ["10:00","12:00","14:00","16:00","18:00","20:00","22:00"]
            time_grp = (
                filtered_occ.groupby(time_col)[occ_col]
                .mean().mul(100).round(1)
                .reindex(time_order).reset_index()
            )
            time_grp.columns = [time_col, "Avg Occupancy (%)"]
            fig_time = px.bar(
                time_grp, x=time_col, y="Avg Occupancy (%)",
                labels={time_col: "Time Slot"},
                color="Avg Occupancy (%)",
                color_continuous_scale=["#2e2e2e", GV_GOLD]
            )
            st.plotly_chart(fig_time, use_container_width=True)

        with col_chart4:
            st.subheader("Revenue by Location")
            loc_rev = (
                filtered_occ.groupby(loc_col)[rev_col]
                .sum().div(1000).round(1).reset_index()
                .sort_values(rev_col, ascending=True)
            )
            loc_rev.columns = [loc_col, "Revenue (SGD '000)"]
            fig_loc = px.bar(
                loc_rev, x="Revenue (SGD '000)", y=loc_col,
                orientation="h", color="Revenue (SGD '000)",
                color_continuous_scale=["#2e2e2e", GV_GOLD]
            )
            st.plotly_chart(fig_loc, use_container_width=True)

        # --- ROW 3: Day x Time Slot Heatmap ---
        st.subheader("📊 Occupancy Heatmap — Day × Time Slot")
        pivot = (
            filtered_occ.groupby([day_col, time_col])[occ_col]
            .mean().mul(100).round(1).reset_index()
            .pivot(index=day_col, columns=time_col, values=occ_col)
            .reindex(day_order)
            .reindex(columns=["10:00","12:00","14:00","16:00","18:00","20:00","22:00"])
        )
        fig_heat = px.imshow(
            pivot, text_auto=True, aspect="auto",
            color_continuous_scale=["#1a1a1a", "#7a5200", GV_GOLD],
            labels={"color": "Avg Occupancy (%)"},
        )
        st.plotly_chart(fig_heat, use_container_width=True)

        # --- RAW DATA TOGGLE ---
        st.markdown("---")
        if st.checkbox("Show Raw Bookings Data"):
            st.dataframe(filtered_occ, use_container_width=True)

        # ══════════════════════════════════════════════════
        # SECTION: PREDICTIVE ANALYTICS (LINEAR REGRESSION)
        # ══════════════════════════════════════════════════
        st.markdown("---")
        st.title("🔮 Predictive Analytics")
        st.write(
            "A Linear Regression model trained on **all historical bookings** predicts expected "
            "occupancy based on genre, day of week, time slot, and location. "
            "Results below reflect your currently applied sidebar filters."
        )

        # Features to encode — only include columns that actually exist
        potential_features = [genre_col, day_col, time_col, loc_col]
        lr_features = [col for col in potential_features if col in occ_df.columns]

        if lr_features and occ_col in occ_df.columns:
            # 1. Train on FULL (unfiltered) dataset so the model learns general patterns
            train_df = occ_df.dropna(subset=lr_features + [occ_col]).copy()

            if not train_df.empty:
                # occupancy_rate in this dataset is 0-1; scale to % for readability
                train_df["occ_pct"] = train_df[occ_col] * 100

                X_train = pd.get_dummies(train_df[lr_features], drop_first=True)
                y_train = train_df["occ_pct"]

                lr_model = LinearRegression()
                lr_model.fit(X_train, y_train)

                # 2. Predict on the user's FILTERED subset
                if not filtered_occ.empty:
                    test_df = filtered_occ.dropna(subset=lr_features).copy()
                    test_df["occ_pct"] = test_df[occ_col] * 100

                    if not test_df.empty:
                        X_test = pd.get_dummies(test_df[lr_features], drop_first=True)
                        # Align columns — add any missing dummy columns as 0
                        X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

                        test_df["Predicted Occupancy (%)"] = lr_model.predict(X_test)

                        # --- KPI METRICS ---
                        avg_actual    = test_df["occ_pct"].mean()
                        avg_predicted = test_df["Predicted Occupancy (%)"].mean()
                        delta         = avg_predicted - avg_actual

                        m1, m2, m3 = st.columns(3)
                        m1.metric("Actual Avg Occupancy (Filtered)",  f"{avg_actual:.1f}%")
                        m2.metric("Predicted Avg Occupancy (Model)",  f"{avg_predicted:.1f}%",
                                  delta=f"{delta:+.1f}%")
                        m3.metric("Screenings Analysed",              f"{len(test_df):,}")

                        st.markdown("---")

                        # --- SCATTER: Actual vs Predicted ---
                        col_pred1, col_pred2 = st.columns(2)

                        with col_pred1:
                            st.subheader("Actual vs. Predicted Occupancy")
                            fig_scatter_pred = px.scatter(
                                test_df,
                                x="occ_pct",
                                y="Predicted Occupancy (%)",
                                color=loc_col if loc_col in test_df.columns else None,
                                opacity=0.65,
                                labels={"occ_pct": "Actual Occupancy (%)",
                                        "Predicted Occupancy (%)": "Predicted Occupancy (%)"},
                                color_discrete_sequence=GV_COLORS,
                            )
                            # Perfect-prediction reference line
                            fig_scatter_pred.add_shape(
                                type="line", x0=0, y0=0, x1=100, y1=100,
                                line=dict(dash="dash", color=GV_GOLD, width=1.5)
                            )
                            fig_scatter_pred.add_annotation(
                                x=85, y=80, text="Perfect prediction",
                                showarrow=False, font=dict(color=GV_GOLD, size=11)
                            )
                            st.plotly_chart(fig_scatter_pred, use_container_width=True)

                        # --- BAR: Avg Predicted Occupancy by Genre ---
                        with col_pred2:
                            st.subheader("Predicted Occupancy by Genre")
                            if genre_col in test_df.columns:
                                genre_pred = (
                                    test_df.groupby(genre_col)["Predicted Occupancy (%)"]
                                    .mean().round(1).reset_index()
                                    .sort_values("Predicted Occupancy (%)", ascending=False)
                                )
                                fig_genre_pred = px.bar(
                                    genre_pred,
                                    x=genre_col, y="Predicted Occupancy (%)",
                                    color=genre_col,
                                    color_discrete_sequence=GV_COLORS,
                                    labels={genre_col: "Genre"}
                                )
                                fig_genre_pred.update_layout(showlegend=False)
                                st.plotly_chart(fig_genre_pred, use_container_width=True)

                        # --- LINE + BAR: Predicted by Day & Time Slot ---
                        col_pred3, col_pred4 = st.columns(2)

                        with col_pred3:
                            st.subheader("Predicted Occupancy by Day of Week")
                            if day_col in test_df.columns:
                                day_pred = (
                                    test_df.groupby(day_col)["Predicted Occupancy (%)"]
                                    .mean().round(1)
                                    .reindex(day_order).reset_index()
                                )
                                day_pred.columns = [day_col, "Predicted Occupancy (%)"]
                                fig_day_pred = px.line(
                                    day_pred, x=day_col, y="Predicted Occupancy (%)",
                                    markers=True,
                                    labels={day_col: "Day of Week"},
                                    color_discrete_sequence=[GV_GOLD]
                                )
                                fig_day_pred.update_traces(line_width=2.5, marker_size=8)
                                st.plotly_chart(fig_day_pred, use_container_width=True)

                        with col_pred4:
                            st.subheader("Predicted Occupancy by Time Slot")
                            if time_col in test_df.columns:
                                time_pred = (
                                    test_df.groupby(time_col)["Predicted Occupancy (%)"]
                                    .mean().round(1)
                                    .reindex(time_order).reset_index()
                                )
                                time_pred.columns = [time_col, "Predicted Occupancy (%)"]
                                fig_time_pred = px.bar(
                                    time_pred, x=time_col, y="Predicted Occupancy (%)",
                                    labels={time_col: "Time Slot"},
                                    color="Predicted Occupancy (%)",
                                    color_continuous_scale=["#2e2e2e", GV_GOLD]
                                )
                                st.plotly_chart(fig_time_pred, use_container_width=True)

                        # --- FEATURE IMPORTANCE ---
                        st.markdown("---")
                        st.subheader("📐 Model Feature Importance")
                        st.caption(
                            "Magnitude of Linear Regression coefficients — larger bars indicate "
                            "stronger influence on predicted occupancy."
                        )
                        coef_df = (
                            pd.DataFrame({
                                "Feature":     X_train.columns,
                                "Coefficient": lr_model.coef_
                            })
                            .assign(Abs=lambda d: d["Coefficient"].abs())
                            .sort_values("Abs", ascending=False)
                            .head(20)
                        )
                        fig_coef = px.bar(
                            coef_df, x="Coefficient", y="Feature",
                            orientation="h",
                            color="Coefficient",
                            color_continuous_scale=["#c98a0a", "#1a1a1a", GV_GOLD],
                            labels={"Coefficient": "Coefficient Value", "Feature": "Feature"}
                        )
                        fig_coef.update_layout(yaxis=dict(autorange="reversed"))
                        st.plotly_chart(fig_coef, use_container_width=True)

                    else:
                        st.warning("Filtered data has missing values in required feature columns — prediction unavailable.")
                else:
                    st.warning("No data matches the selected filters. Adjust the sidebar filters to see predictions.")
            else:
                st.error("Not enough training data to fit the model.")
        else:
            st.error("Required feature columns or 'occupancy_rate' are missing from the dataset.")
