import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import os

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="Golden Village Analytics", layout="wide")

# --- DATA LOADING (CACHED) ---
@st.cache_data
def load_data():
    """
    Loads all CSV data from the data/ folder.
    gv_customer_segments.csv is generated by running gv_analytics_main.py first.
    """
    try:
        movies_df    = pd.read_csv("data/gv_movies.csv")
        customers_df = pd.read_csv("data/gv_customers_v3.csv")
        bookings_df  = pd.read_csv("data/gv_bookings.csv", parse_dates=["screening_date"])

        # Derive occupancy_rate if not already present
        if "occupancy_rate" not in bookings_df.columns:
            bookings_df["occupancy_rate"] = bookings_df["seats_sold"] / bookings_df["capacity"]

        # gv_bookings.csv already contains genre, title, day_of_week, time_slot, occupancy_rate
        # so we only need movies_df for any extra movie-level columns (e.g. rating, duration)
        occ_df = bookings_df.copy()

        # Load segments if available (generated by gv_analytics_main.py)
        segments_path = "data/gv_customer_segments.csv"
        if os.path.exists(segments_path):
            segments_df  = pd.read_csv(segments_path)
            cust_seg_df  = pd.merge(customers_df, segments_df[["customer_id","persona"]],
                                    on="customer_id", how="left")
        else:
            # Fall back to customers only — persona column will be missing
            cust_seg_df = customers_df.copy()
            cust_seg_df["persona"] = "Run gv_analytics_main.py to generate segments"

        return movies_df, cust_seg_df, occ_df

    except FileNotFoundError as e:
        st.error(f"Data file not found: {e}. Ensure you are running this from the root directory and the data/ folder exists.")
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame()

# Load data
movies_df, cust_seg_df, occ_df = load_data()

# --- SIDEBAR NAVIGATION ---
st.sidebar.title("GV Analytics Menu")
page = st.sidebar.radio("Select Dashboard:", ["Customer Clustering", "Occupancy Analytics"])

# ══════════════════════════════════════════════════
# PAGE 1: CUSTOMER CLUSTERING
# ══════════════════════════════════════════════════
if page == "Customer Clustering":
    st.title("👥 Customer Clustering & Segmentation")

    if not cust_seg_df.empty:
        # Column names from gv_customers_v3.csv + gv_customer_segments.csv
        segment_col = "persona"           # from gv_customer_segments.csv export
        spend_col   = "total_spend"       # from gv_customers_v3.csv
        freq_col    = "total_visits"      # from gv_customers_v3.csv
        genre_col   = "favourite_genre"   # from gv_customers_v3.csv

        # --- SIDEBAR FILTERS ---
        st.sidebar.subheader("Clustering Filters")

        segment_options = cust_seg_df[segment_col].dropna().unique()
        selected_segments = st.sidebar.multiselect(
            "Select Customer Segments:",
            options=segment_options,
            default=segment_options
        )
        filtered_cust = cust_seg_df[cust_seg_df[segment_col].isin(selected_segments)]

        # --- KPIs ---
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Total Customers",  f"{len(filtered_cust):,}")
        col2.metric("Average Spend",    f"${filtered_cust[spend_col].mean():.2f}")
        col3.metric("Avg Visits",       f"{filtered_cust[freq_col].mean():.1f}")
        col4.metric("GV+ Members",
                    f"{filtered_cust['gv_plus_member'].sum():,}" if "gv_plus_member" in filtered_cust.columns else "N/A")

        st.markdown("---")

        # --- ROW 1: Segment Distribution + Spend vs Frequency ---
        col_chart1, col_chart2 = st.columns(2)

        with col_chart1:
            st.subheader("Segment Distribution")
            seg_counts = filtered_cust[segment_col].value_counts().reset_index()
            seg_counts.columns = [segment_col, "count"]
            fig_bar = px.bar(
                seg_counts, x=segment_col, y="count",
                labels={segment_col: "Segment", "count": "Number of Customers"},
                color=segment_col
            )
            fig_bar.update_layout(showlegend=False, xaxis_tickangle=-20)
            st.plotly_chart(fig_bar, use_container_width=True)

        with col_chart2:
            st.subheader("Spend vs. Visit Frequency by Segment")
            fig_scatter = px.scatter(
                filtered_cust, x=freq_col, y=spend_col,
                color=segment_col, hover_data=["customer_id"],
                labels={freq_col: "Total Visits", spend_col: "Total Spend (SGD)"},
                opacity=0.6
            )
            st.plotly_chart(fig_scatter, use_container_width=True)

        # --- ROW 2: Avg Spend per Segment + Favourite Genre Breakdown ---
        col_chart3, col_chart4 = st.columns(2)

        with col_chart3:
            st.subheader("Avg Spend & Visits per Segment")
            profile_df = (
                filtered_cust.groupby(segment_col)[[spend_col, freq_col, "avg_ticket_price"]]
                .mean().round(2).reset_index()
            )
            fig_profile = px.bar(
                profile_df, x=segment_col, y=spend_col,
                color=segment_col,
                labels={segment_col: "Segment", spend_col: "Avg Total Spend (SGD)"}
            )
            fig_profile.update_layout(showlegend=False, xaxis_tickangle=-20)
            st.plotly_chart(fig_profile, use_container_width=True)

        with col_chart4:
            st.subheader("Favourite Genre by Segment")
            if genre_col in filtered_cust.columns:
                genre_seg = (
                    filtered_cust.groupby([segment_col, genre_col])
                    .size().reset_index(name="count")
                )
                fig_genre = px.bar(
                    genre_seg, x=genre_col, y="count",
                    color=segment_col, barmode="group",
                    labels={genre_col: "Genre", "count": "Customers"}
                )
                fig_genre.update_layout(xaxis_tickangle=-20)
                st.plotly_chart(fig_genre, use_container_width=True)
            else:
                st.info("Favourite genre column not found.")

        # --- SEGMENT PROFILE TABLE ---
        st.markdown("---")
        st.subheader("📋 Segment Profile Summary")
        profile_table = (
            filtered_cust.groupby(segment_col)
            .agg(
                Customers      =(segment_col,   "count"),
                Avg_Spend      =(spend_col,      "mean"),
                Avg_Visits     =(freq_col,       "mean"),
                Avg_Recency    =("recency_days", "mean") if "recency_days" in filtered_cust.columns else (spend_col, "count"),
                GVPlus_Rate    =("gv_plus_member","mean") if "gv_plus_member" in filtered_cust.columns else (spend_col, "count"),
            )
            .round(2)
            .reset_index()
        )
        st.dataframe(profile_table, use_container_width=True)

# ══════════════════════════════════════════════════
# PAGE 2: OCCUPANCY ANALYTICS
# ══════════════════════════════════════════════════
elif page == "Occupancy Analytics":
    st.title("🍿 Occupancy Analytics")

    if not occ_df.empty:
        # Column names from gv_bookings.csv
        genre_col   = "genre"           # already in bookings CSV
        day_col     = "day_of_week"     # already in bookings CSV
        time_col    = "time_slot"       # already in bookings CSV
        loc_col     = "location"        # already in bookings CSV
        occ_col     = "occupancy_rate"  # derived or already present
        rev_col     = "revenue"         # already in bookings CSV
        title_col   = "title"           # already in bookings CSV

        # --- SIDEBAR FILTERS ---
        st.sidebar.subheader("Occupancy Filters")

        selected_genres = st.sidebar.multiselect(
            "Filter by Genre:",
            options=sorted(occ_df[genre_col].dropna().unique()),
            default=sorted(occ_df[genre_col].dropna().unique())
        )

        day_order = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
        available_days = [d for d in day_order if d in occ_df[day_col].unique()]
        selected_days = st.sidebar.multiselect(
            "Filter by Day:",
            options=available_days,
            default=available_days
        )

        selected_locations = st.sidebar.multiselect(
            "Filter by Location:",
            options=sorted(occ_df[loc_col].dropna().unique()),
            default=sorted(occ_df[loc_col].dropna().unique())
        )

        # Apply filters
        filtered_occ = occ_df[
            occ_df[genre_col].isin(selected_genres) &
            occ_df[day_col].isin(selected_days) &
            occ_df[loc_col].isin(selected_locations)
        ]

        # --- KPIs ---
        col1, col2, col3, col4 = st.columns(4)
        top_movie   = filtered_occ[title_col].value_counts().index[0] if len(filtered_occ) > 0 else "N/A"
        total_rev   = filtered_occ[rev_col].sum() if rev_col in filtered_occ.columns else 0
        avg_occ     = filtered_occ[occ_col].mean() * 100 if len(filtered_occ) > 0 else 0

        col1.metric("Total Bookings",      f"{len(filtered_occ):,}")
        col2.metric("Avg. Occupancy Rate", f"{avg_occ:.1f}%")
        col3.metric("Total Revenue",       f"SGD {total_rev/1_000_000:.2f}M" if total_rev > 0 else "N/A")
        col4.metric("Top Movie",           top_movie)

        st.markdown("---")

        # --- ROW 1: Occupancy by Genre + Day of Week Trend ---
        col_chart1, col_chart2 = st.columns(2)

        with col_chart1:
            st.subheader("Avg Occupancy by Genre")
            genre_grp = (
                filtered_occ.groupby(genre_col)[occ_col]
                .mean().mul(100).round(1).reset_index()
                .sort_values(occ_col, ascending=False)
            )
            genre_grp.columns = [genre_col, "Avg Occupancy (%)"]
            fig_genre = px.bar(
                genre_grp, x=genre_col, y="Avg Occupancy (%)",
                color=genre_col,
                labels={genre_col: "Genre"}
            )
            fig_genre.update_layout(showlegend=False)
            st.plotly_chart(fig_genre, use_container_width=True)

        with col_chart2:
            st.subheader("Avg Occupancy by Day of Week")
            day_grp = (
                filtered_occ.groupby(day_col)[occ_col]
                .mean().mul(100).round(1)
                .reindex(day_order).reset_index()
            )
            day_grp.columns = [day_col, "Avg Occupancy (%)"]
            fig_day = px.line(
                day_grp, x=day_col, y="Avg Occupancy (%)",
                markers=True,
                labels={day_col: "Day of Week"}
            )
            st.plotly_chart(fig_day, use_container_width=True)

        # --- ROW 2: Occupancy by Time Slot + Location Heatmap ---
        col_chart3, col_chart4 = st.columns(2)

        with col_chart3:
            st.subheader("Avg Occupancy by Time Slot")
            time_order = ["10:00","12:00","14:00","16:00","18:00","20:00","22:00"]
            time_grp = (
                filtered_occ.groupby(time_col)[occ_col]
                .mean().mul(100).round(1)
                .reindex(time_order).reset_index()
            )
            time_grp.columns = [time_col, "Avg Occupancy (%)"]
            fig_time = px.bar(
                time_grp, x=time_col, y="Avg Occupancy (%)",
                labels={time_col: "Time Slot"},
                color="Avg Occupancy (%)",
                color_continuous_scale="YlOrRd"
            )
            st.plotly_chart(fig_time, use_container_width=True)

        with col_chart4:
            st.subheader("Revenue by Location")
            loc_rev = (
                filtered_occ.groupby(loc_col)[rev_col]
                .sum().div(1000).round(1).reset_index()
                .sort_values(rev_col, ascending=True)
            )
            loc_rev.columns = [loc_col, "Revenue (SGD '000)"]
            fig_loc = px.bar(
                loc_rev, x="Revenue (SGD '000)", y=loc_col,
                orientation="h", color="Revenue (SGD '000)",
                color_continuous_scale="Blues"
            )
            st.plotly_chart(fig_loc, use_container_width=True)

        # --- ROW 3: Day x Time Slot Heatmap ---
        st.subheader("📊 Occupancy Heatmap — Day × Time Slot")
        pivot = (
            filtered_occ.groupby([day_col, time_col])[occ_col]
            .mean().mul(100).round(1).reset_index()
            .pivot(index=day_col, columns=time_col, values=occ_col)
            .reindex(day_order)
            .reindex(columns=["10:00","12:00","14:00","16:00","18:00","20:00","22:00"])
        )
        fig_heat = px.imshow(
            pivot, text_auto=True, aspect="auto",
            color_continuous_scale="YlOrRd",
            labels={"color": "Avg Occupancy (%)"},
        )
        st.plotly_chart(fig_heat, use_container_width=True)

        # --- RAW DATA TOGGLE ---
        st.markdown("---")
        if st.checkbox("Show Raw Bookings Data"):
            st.dataframe(filtered_occ, use_container_width=True)
